---
name: PrivacyPass Challenge Extension

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    name: Running on Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 16]
    steps:
      - name: Checking out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Building
        run: npm run build
      - name: Testing
        run: npm test
